using MathClubTracker.Domain;
using MathClubTracker.Domain.DomainObjects;
//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for NHibernate model.
// Code is generated on: 10/6/2013 4:01:09 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace MathClubTracker.NHibernate
{
    public partial interface IStudentRepository : IRepository<Student>
    {


        void InitializeData();

        List<Student> Search(Domain.Search.StudentSearchCriteria criteria);


        IEnumerable<Student> GetPaged(int skip, int top, string orderby);


        IList<Student> GetAttendeesByDate(DateTime sessionDate);
        int GetStudentCount();

        Student GetByMathGeniusId(int id);
    }
}
